# Generated by Django 5.0 on 2023-12-16 19:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, null=True, unique=True)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('highest_qualification', models.CharField(max_length=50, null=True)),
                ('employment_status', models.CharField(max_length=50, null=True)),
                ('state_of_residence', models.CharField(max_length=50, null=True)),
                ('nationality', models.CharField(max_length=50, null=True)),
                ('area_of_specialization', models.CharField(max_length=100, null=True)),
                ('personal_statement', models.TextField(max_length=5000, null=True)),
                ('availability', models.CharField(max_length=50, null=True)),
                ('working_hours', models.CharField(max_length=500, null=True)),
                ('status', models.BooleanField(null=True)),
                ('cv_id', models.IntegerField(null=True, unique=True)),
                ('profile_picture', models.CharField(max_length=300, unique=True)),
                ('residential_address', models.CharField(max_length=255, null=True)),
                ('active_clients', models.IntegerField(default=0, null=True)),
                ('total_clients', models.IntegerField(default=0, null=True)),
                ('rejected_clients', models.IntegerField(default=0, null=True)),
                ('reviews_id', models.IntegerField(null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('number_of_tutors', models.IntegerField(null=True)),
                ('related_subjects', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('tutors', models.ManyToManyField(null=True, related_name='subjects', to='tutor.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='ProCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_course_name', models.CharField(max_length=100)),
                ('number_of_tutors', models.IntegerField(null=True)),
                ('related_pro_courses', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('tutors', models.ManyToManyField(null=True, related_name='pto_courses', to='tutor.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='TutorReportAbuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_client_id', models.IntegerField()),
                ('message', models.CharField(max_length=400)),
                ('subject', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ManyToManyField(null=True, related_name='reported_client', to='tutor.tutor')),
            ],
        ),
    ]
