# Generated by Django 5.0 on 2023-12-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procourse',
            name='tutors',
            field=models.ManyToManyField(related_name='pro_courses', to='tutor.tutor'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='tutors',
            field=models.ManyToManyField(related_name='subjects', to='tutor.tutor'),
        ),
        migrations.AlterField(
            model_name='tutorreportabuse',
            name='tutor',
            field=models.ManyToManyField(related_name='reported_client', to='tutor.tutor'),
        ),
    ]
