# Generated by Django 5.0 on 2023-12-17 11:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tutor', '0002_alter_procourse_tutors_alter_subject_tutors_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='tutor',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='user',
        ),
        migrations.AddField(
            model_name='tutor',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='groups',
            field=models.ManyToManyField(related_name='tutor_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='user_permissions',
            field=models.ManyToManyField(related_name='tutor_permissions', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='username',
            field=models.CharField(default=1, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='first_name',
            field=models.CharField(blank=True, default=1, max_length=150, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutor',
            name='last_name',
            field=models.CharField(blank=True, default=1, max_length=150, verbose_name='last name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutor',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='profile_picture',
            field=models.ImageField(default='templates/lessonpedia/static/images/user/default_user_icon.png', upload_to='profile_picture/'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='working_hours',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tutorreportabuse',
            name='message',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='tutorreportabuse',
            name='tutor',
        ),
        migrations.AddField(
            model_name='tutorreportabuse',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reported_client', to='tutor.tutor'),
            preserve_default=False,
        ),
    ]
