# Generated by Django 5.0 on 2023-12-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appadmin',
            name='profile_picture',
            field=models.ImageField(default='templates/lessonpedia/static/images/user/default_user_icon.png', upload_to='profile_picture/'),
        ),
    ]
