# Generated by Django 5.0 on 2024-01-05 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('client', '0001_initial'),
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='target_tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selling_tutor', to='tutor.tutor'),
        ),
        migrations.AddField(
            model_name='client',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='client_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='client',
            name='tutor',
            field=models.ManyToManyField(related_name='engaged_tutor', to='tutor.tutor'),
        ),
        migrations.AddField(
            model_name='client',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='client_permissions', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='cart',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='client.client'),
        ),
        migrations.AddField(
            model_name='clientreportabuse',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abuse_reports', to='client.client'),
        ),
        migrations.AddField(
            model_name='clientreportabuse',
            name='target_tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_tutor', to='tutor.tutor'),
        ),
        migrations.AddField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='client.client'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_receipts', to='client.client'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rankings', to='client.client'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rankings', to='tutor.tutor'),
        ),
        migrations.AddField(
            model_name='review',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='client.client'),
        ),
        migrations.AddField(
            model_name='review',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='tutor.tutor'),
        ),
    ]
