# Generated by Django 5.0 on 2024-01-09 20:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentreceipt',
            name='client',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceNumber', models.IntegerField(null=True)),
                ('tnx_id', models.IntegerField(null=True)),
                ('tnx_status', models.CharField(max_length=200, null=True)),
                ('tnx_amount', models.FloatField(null=True)),
                ('tnx_message', models.CharField(max_length=200, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='client.client')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='tutor.tutor')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentReceipt',
        ),
    ]
