# Generated by Django 5.0 on 2024-01-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_paymentreceipt_client_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='referenceNumber',
            field=models.BigIntegerField(null=True),
        ),
    ]
