# Generated by Django 5.0 on 2023-12-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='others',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
