# Generated by Django 5.0 on 2024-01-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreportabuse',
            name='resolved_by_admin',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='review_subject',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='rank_number',
            field=models.IntegerField(null=True),
        ),
    ]
