# Generated by Django 4.2.7 on 2023-12-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='client_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='client_permissions', to='auth.permission'),
        ),
    ]
