# Generated by Django 5.0 on 2024-01-06 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_clientreportabuse_resolved_by_admin_and_more'),
        ('tutor', '0008_delete_tutorreportabuse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='target_tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='tutor.tutor'),
        ),
        migrations.DeleteModel(
            name='ClientReportAbuse',
        ),
    ]
