# Generated by Django 5.0 on 2024-01-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_transaction_referencenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tnx_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
