# Generated by Django 5.0 on 2023-12-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(default='images/user/default_user_icon.png', upload_to='profile_picture/'),
        ),
    ]
