# Generated by Django 5.0 on 2023-12-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_deactivatebyclient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='suspension_duration',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
