# Generated by Django 4.2.7 on 2023-12-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='tutor',
        ),
    ]
