# Generated by Django 5.0 on 2023-12-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_block_reason_admin_client_blocked_at_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='tutor_status',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='tutors_count',
        ),
        migrations.AddField(
            model_name='cart',
            name='contract_validated_start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='contract_validity',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='contract_validity_end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
