# Generated by Django 5.0 on 2024-01-10 16:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_cart_target_tutor_delete_clientreportabuse'),
        ('tutor', '0012_tutor_marital_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentreceipt',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='prefered_channel',
            field=models.CharField(choices=[('-- select --', '-- select --'), ('Online', 'Online'), ('Physical', 'Physical'), ('Hybrid', 'Hybrid')], default='-- select --', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='prefered_language',
            field=models.CharField(choices=[('-- select --', '-- select --'), ('English', 'English'), ('French', 'French'), ('Spanish', 'Spanish'), ('Igbo', 'Igbo'), ('Yoruba', 'Yoruba'), ('Hausa', 'Hausa')], default='-- select --', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='prefered_tutor_gender',
            field=models.CharField(choices=[('-- select --', '-- select --'), ('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], default='-- select --', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='specific_educational_level',
            field=models.CharField(choices=[('choose educational level', 'choose educational level'), ('Primary 1', 'Primary 1'), ('Primary 2', 'Primary 2'), ('Primary 3', 'Primary 3'), ('Primary 4', 'Primary 4'), ('Primary 5', 'Primary 5'), ('Primary 6', 'Primary 6'), ('JSS 1', 'JSS 1'), ('JSS 2', 'JSS 2'), ('JSS 3', 'JSS 3'), ('SSS 1', 'SSS 1'), ('SSS 2', 'SSS 2'), ('SSS 3', 'SSS 3'), ('University 100L', 'University 100L'), ('University 200L', 'University 200L'), ('University 300L', 'University 300L'), ('University 400L', 'University 400L'), ('University 500L', 'University 500L'), ('ND 1', 'ND 1'), ('ND 2', 'ND 2'), ('HND 1', 'HND 1'), ('HND 2', 'HND 2'), ('Masters', 'Masters'), ('PgD', 'PgD'), ('PhD', 'PhD'), ('Others', 'Others')], default='choose educational level', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='target_tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selling_tutor', to='tutor.tutor'),
        ),
        migrations.AlterField(
            model_name='client',
            name='educational_level',
            field=models.CharField(choices=[('-- select --', '-- select --'), ('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Tertiary', 'Tertiary'), ('Others', 'Others')], default='-- select --', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('-- select --', '-- select --'), ('Male', 'Male'), ('Female', 'Female')], default='-- select --', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='others',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceNumber', models.BigIntegerField(null=True)),
                ('tnx_id', models.BigIntegerField(null=True)),
                ('tnx_status', models.CharField(max_length=200, null=True)),
                ('tnx_amount', models.FloatField(null=True)),
                ('tnx_message', models.CharField(max_length=200, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='client.client')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='tutor.tutor')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentReceipt',
        ),
    ]
