# Generated by Django 5.0 on 2023-12-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_blocked_at_client_is_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='block_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
