# Generated by Django 5.0 on 2023-12-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='deactivateByClient',
            field=models.BooleanField(default=True),
        ),
    ]
