# Generated by Django 5.0 on 2024-01-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_cart_tutor_status_remove_cart_tutors_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreportabuse',
            name='resolved_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='clientreportabuse',
            name='resolved_by_admin',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
