# Generated by Django 5.0 on 2023-12-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_cart_tutor_status_remove_cart_tutors_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='rank_number',
            field=models.IntegerField(null=True),
        ),
    ]
