# Generated by Django 5.0 on 2024-01-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_paymentreceipt_client_client_prefered_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='rank_number',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
