# Generated by Django 4.2.7 on 2023-12-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_alter_tutor_groups_alter_tutor_user_permissions'),
        ('client', '0005_remove_client_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tutor',
            field=models.ManyToManyField(related_name='engaged_tutor', to='tutor.tutor'),
        ),
    ]
