# Generated by Django 4.2.7 on 2023-12-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_client_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='ranking_text',
        ),
        migrations.AddField(
            model_name='ranking',
            name='rank_number',
            field=models.IntegerField(choices=[(1, 'First Option'), (2, 'Second Option'), (3, 'Third Option'), (4, 'Fourth Option'), (5, 'Fifth Option')], null=True),
        ),
    ]
