# Generated by Django 4.2.7 on 2023-12-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_remove_ranking_ranking_text_ranking_rank_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='rank_number',
            field=models.IntegerField(choices=[('First Option', 1), ('Second Option', 2), ('Third Option', 3), ('Fourth Option', 4), ('Fifth Option', 5)], null=True),
        ),
    ]
