# Generated by Django 4.2.7 on 2023-12-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_ranking_rank_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='rank_number',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
