# Generated by Django 5.0 on 2023-12-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_client_date_of_birth_client_educational_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
