# Generated by Django 4.2.7 on 2023-12-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_alter_appadmin_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appadmin',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
