# Generated by Django 4.2.7 on 2023-12-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_alter_appadmin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appadmin',
            name='profile_picture',
            field=models.ImageField(default='default_user_icon.png', upload_to='profile_picture/'),
        ),
    ]
