# Generated by Django 5.0 on 2024-01-08 13:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReportAbuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000)),
                ('subject', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by_admin', models.BooleanField(default=False, null=True)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abuse_reports', to='client.client')),
                ('target_tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_tutor', to='tutor.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_code', models.CharField(max_length=10, unique=True)),
                ('pay_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_made', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_remaining', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract_length', models.IntegerField()),
                ('week_days', models.CharField(default='Mon', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_remaining', models.IntegerField()),
                ('contract_status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Settled', 'Settled'), ('Declined', 'Declined'), ('Terminated', 'Terminated')], default='Pending', max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='client.client')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.subject')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='tutor.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='TutorReportAbuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000)),
                ('subject', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by_admin', models.BooleanField(default=False, null=True)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('target_client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_client', to='client.client')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abuse_reports', to='tutor.tutor')),
            ],
        ),
    ]
