# Generated by Django 5.0 on 2024-01-05 00:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_code', models.CharField(max_length=10, unique=True)),
                ('pay_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_made', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_remaining', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract_length', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_remaining', models.IntegerField()),
                ('contract_status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Completed', 'Completed'), ('Terminated', 'Terminated')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='client.client')),
            ],
        ),
    ]
