# Generated by Django 5.0 on 2024-01-05 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generic_apps', '0001_initial'),
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.subject'),
        ),
        migrations.AddField(
            model_name='contract',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='tutor.tutor'),
        ),
    ]
