# Generated by Django 5.0 on 2024-01-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_apps', '0003_alter_contract_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='week_days',
            field=models.CharField(default='Mon', max_length=100),
        ),
    ]
