# Generated by Django 5.0 on 2024-01-06 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_cart_target_tutor_delete_clientreportabuse'),
        ('generic_apps', '0006_contract_remark'),
        ('tutor', '0008_delete_tutorreportabuse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAbuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=400)),
                ('resolved_by_admin', models.BooleanField(default=False, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abuse_reports', to='client.client')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abuse_reports', to='tutor.tutor')),
            ],
        ),
    ]
