# Generated by Django 5.0 on 2024-01-07 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_cart_target_tutor_delete_clientreportabuse'),
        ('generic_apps', '0007_reportabuse'),
        ('tutor', '0009_remove_tutor_available_time_slots_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReportAbuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000)),
                ('subject', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by_admin', models.BooleanField(default=False, null=True)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abuse_reports', to='client.client')),
                ('target_tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_tutor', to='tutor.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='TutorReportAbuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000)),
                ('subject', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by_admin', models.BooleanField(default=False, null=True)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('target_client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_client', to='client.client')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abuse_reports', to='tutor.tutor')),
            ],
        ),
        migrations.DeleteModel(
            name='ReportAbuse',
        ),
    ]
