# Generated by Django 5.0 on 2024-01-05 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='active_clients',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='rejected_clients',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='total_clients',
        ),
    ]
