# Generated by Django 5.0 on 2023-12-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='highest_qualification',
            field=models.CharField(choices=[('--select one--', '--select one--'), ('Phd', 'Phd'), ('Msc', 'Msc'), ('Bsc', 'Bsc'), ('Beng', 'Beng'), ('Hnd', 'Hnd'), ('ND', 'ND'), ('NCE', 'NCE'), ('Waec', 'Waec'), ('Others', 'Others')], default='--select one--', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='profile_picture',
            field=models.ImageField(default='templates/lessonpedia/static/images/user/default_user_icon.png', upload_to='profile_picture/'),
        ),
    ]
