# Generated by Django 5.0 on 2023-12-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='assessment_score',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='primary_subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
