# Generated by Django 4.2.7 on 2023-12-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_alter_tutor_groups_alter_tutor_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('sciences', 'Sciences'), ('programming', 'Programming'), ('mathematics', 'Mathematics'), ('language_arts', 'Language Arts'), ('history', 'History'), ('music', 'Music'), ('art', 'Art'), ('physical_education', 'Physical Education'), ('social_studies', 'Social Studies'), ('business', 'Business'), ('technology', 'Technology'), ('foreign_language', 'Foreign Language'), ('health', 'Health'), ('philosophy', 'Philosophy'), ('others', 'Others')], max_length=25, null=True),
        ),
    ]
