# Generated by Django 4.2.7 on 2023-12-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_alter_tutor_highest_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='discipline',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='institution',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='others',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
