# Generated by Django 5.0 on 2023-12-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_subject_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='highest_qualification',
            field=models.CharField(choices=[('Phd', 'Phd'), ('Msc', 'Msc'), ('Bsc', 'Bsc'), ('Beng', 'Beng'), ('Hnd', 'Hnd'), ('ND', 'ND'), ('NCE', 'NCE'), ('Waec', 'Waec'), ('Others', 'Others')], max_length=50, null=True),
        ),
    ]
