# Generated by Django 5.0 on 2024-01-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_rename_rejected_contract_count_tutor_declined_contract_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='pending_contract_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
