# Generated by Django 4.2.7 on 2023-12-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_subject_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='profile_picture',
            field=models.ImageField(default='default_user_icon.png', height_field=300, upload_to='profile_picture/', width_field=300),
        ),
    ]
