# Generated by Django 5.0 on 2023-12-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_alter_tutor_primary_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='accumulated_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutor',
            name='rank',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
