# Generated by Django 5.0 on 2023-12-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_alter_tutor_highest_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='highest_qualification',
            field=models.CharField(choices=[('--select one--', '--select one--'), ('Phd', 'Phd'), ('Msc', 'Msc'), ('Bsc', 'Bsc'), ('Beng', 'Beng'), ('Hnd', 'Hnd'), ('ND', 'ND'), ('NCE', 'NCE'), ('Waec', 'Waec'), ('Others', 'Others')], default='--select one--', max_length=50, null=True),
        ),
    ]
