# Generated by Django 4.2.7 on 2023-12-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_tutor_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificate_files/'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='cv_id',
            field=models.FileField(blank=True, null=True, upload_to='cv_files/'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='profile_picture',
            field=models.ImageField(default='default_user_icon.png', upload_to='profile_picture/'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='result',
            field=models.CharField(blank=True, choices=[('--select one--', '--select one--'), ('first_class', 'First Class'), ('distinction', 'Distinction'), ('second_class_upper', 'Second Class Upper'), ('upper_credit', 'Upper Credit'), ('second_class_lower', 'Second Class Lower'), ('lower_credit', 'Lower Credit'), ('others', 'Others')], default='--select one--', max_length=20, null=True),
        ),
    ]
