# Generated by Django 4.2.7 on 2023-12-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_alter_tutor_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='profile_picture',
            field=models.ImageField(default='default_user_icon.png', upload_to='profile_picture/'),
        ),
    ]
