# Generated by Django 5.0 on 2024-01-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_tutor_total_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='received_payment',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
