# Generated by Django 4.2.7 on 2023-12-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_tutor_certificate_alter_tutor_cv_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='employment_status',
        ),
        migrations.AddField(
            model_name='tutor',
            name='employment_type',
            field=models.CharField(choices=[('--select one--', '--select one--'), ('full_time', 'Full Time'), ('part_time', 'Part Time'), ('freelance', 'Freelance'), ('others', 'Others')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='institution_type',
            field=models.CharField(choices=[('--select one--', '--select one--'), ('university', 'University'), ('polytechnic', 'Polytechnic'), ('COE', 'College Of Education'), ('vocational', 'Vocational'), ('others', 'Others')], default='--select one--', max_length=20, null=True),
        ),
    ]
