# Generated by Django 5.0 on 2023-12-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_tutor_accumulated_rating_tutor_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='rank',
            field=models.FloatField(default=1.0, null=True),
        ),
    ]
