# Generated by Django 5.0 on 2024-01-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_tutor_received_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='cart_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
