# Generated by Django 4.2.7 on 2023-12-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_remove_tutor_employment_status_tutor_employment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='employment_status',
            field=models.CharField(choices=[('', '--select one--'), ('Employed', 'Employed'), ('Self Employed', 'Self Employed'), ('Unemployed', 'Unemployed')], default='--select one--', max_length=50, null=True),
        ),
    ]
