# Generated by Django 5.0 on 2023-12-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_alter_tutor_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='assessment_score',
        ),
        migrations.AddField(
            model_name='tutor',
            name='quiz_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='quiz_result',
            field=models.FloatField(null=True),
        ),
    ]
