# Generated by Django 4.2.7 on 2023-12-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_tutor_employment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='lga_resident',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
