# Generated by Django 4.2.7 on 2023-12-26 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_tutor_lga_resident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='gender',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, null=True),
        ),
    ]
