# Generated by Django 5.0 on 2024-01-07 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_delete_tutorreportabuse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='available_time_slots',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tutor.tutor'),
        ),
    ]
