# Generated by Django 5.0 on 2023-12-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_tutor_blocked_at_tutor_is_blocked_tutor_is_suspended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='block_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
