# Generated by Django 5.0 on 2023-12-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_remove_tutor_assessment_score_tutor_quiz_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
    ]
