# Generated by Django 5.0 on 2024-01-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0009_remove_tutor_available_time_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='price_per_hour',
            field=models.IntegerField(default=500, null=True),
        ),
    ]
