# Generated by Django 5.0 on 2023-12-30 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0009_tutor_suspended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='suspended',
            new_name='is_suspended',
        ),
    ]
