# Generated by Django 5.0 on 2023-12-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0010_rename_suspended_tutor_is_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
