# Generated by Django 5.0 on 2024-01-03 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0012_tutor_block_reason_admin_tutor_blocked_at_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorreportabuse',
            name='resolved_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tutorreportabuse',
            name='resolved_by_admin',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tutorreportabuse',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abuse_reports', to='tutor.tutor'),
        ),
    ]
