# Generated by Django 5.0 on 2024-01-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0012_tutor_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='open_to_work',
            field=models.CharField(choices=[('', '--select one--'), ('Open', 'Open'), ('Not open to work', 'Not open to work'), ('Engaged', 'Engaged')], default='Open', max_length=50, null=True),
        ),
    ]
